server:
  port: 8080

spring:
  application:
    name: farmhouse-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: farmhouse-user
          uri: lb://farmhouse-user
          predicates:
            - Path=/api/user/**
        - id: farmhouse-merchant
          uri: lb://farmhouse-merchant
          predicates:
            - Path=/api/merchant/**
        - id: farmhouse-product
          uri: lb://farmhouse-product
          predicates:
            - Path=/api/product/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
